version: "3.7"

services:
  memos:
    image: neosmemo/memos:0.24.2
    container_name: memos
    restart: always
    environment:
      - MEMOS_MODE=prod
      - MEMOS_PORT=5230
    ports:
      - "5230:5230"
    volumes:
      - /opt/1panel/apps/memos/memos/memos:/var/opt/memos

  memogram:
    build: .
    container_name: memogram
    restart: always
    environment:
      - BOT_TOKEN=xxxxxxxx:xxxxxxxxxxxx  --修改成你自己的bot token
      - SERVER_ADDR=memos:5230
    depends_on:
      - memos
